# Generated by Django 2.1.2 on 2018-11-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='edad_aproximada',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='mascota',
            name='Descripcion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
