# Generated by Django 2.1 on 2018-11-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20181106_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
